/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    // './public/**/*.html',
    './src/**/*.{js,jsx,ts,tsx,css,scss}',
  ],
  darkMode: 'class', // 'media' is the default, change to 'class' if you want to use dark mode in with class names
  theme: {
    colors: {
      ...require('tailwindcss/colors'),
      'primary-100': '#e6d9ff',
      'primary-200': '#ccb3ff',
      'primary-300': '#b38cff',
      'primary-400': '#9966ff',
      'primary-500': '#8146e0',
      'primary-600': '#6d3cc4',
      'primary-700': '#5e33a9',
      'primary-800': '#512a8f',
      'primary-900': '#462177',
      'primary-1000': '#3b1a5f',
      'primary-bg': '#8146e0',
      'primary-text': '#ffffff',
      'primary-border': '#e6d9ff',
      'primary-hover': '#6d3cc4',

      'primary-dark': '#b39ddb',
      'primary-light': '#8146e0',
      'secondary-dark': '#7986cb',
      'background-dark': '#121212',
      'on-dark-high-emphasis': '#ffffffe6',
      'on-dark-medium-emphasis': '#ffffff99',
      'on-dark-disabled': '#ffffff61',
      'on-light-high-emphasis': '#000000de',
      'on-light-medium-emphasis': '#00000099',
      'on-light-disabled': '#00000061',
      'border-on-dark': '#ffffff1f',
      'content-on-dark-disabled': '#ffffff61',
      'error-dark': '#cf6679',
      'accent-dark': '#c5cae9',
      'brand': '#8146e0',
    },
    extend: {},
  },
  plugins: [require('@tailwindcss/typography')],
}
